#!/bin/bash

. /bin/installer-functions

###################
# INSTALLER STEPS #
###################

function download_initrootfs () {
	local REL="noble"
	local REL_URL="http://cloud-images.ubuntu.com/${REL}/current/"
	local FILE=${REL}-server-cloudimg-riscv64-root.tar.xz
	local DOWNLOAD_URL=${REL_URL}/${FILE}
	local SAVED_PWD=${PWD}

	pr_ann "Downloading base rootfs..."

	mkdir -p ${PREFIX} &> /dev/null
	cd ${PREFIX}
	wget ${DOWNLOAD_URL}

	pr_ann "Unpacking base rootfs..."
#	tar xJpf ${FILE} --xattrs-include='*.*' --numeric-owner &> /dev/null
	tar xJf ${FILE} --numeric-owner &> /dev/null

	rm ${FILE}
	cd ${SAVED_PWD}
}

function initialize_rootfs () {
	pr_ann "Initializing rootfs"

	pr_inf "Installing kernel modules"
	mkdir -p ${PREFIX}/lib/modules
	cp -a /lib/modules/* ${PREFIX}/lib/modules/ &> /dev/null

	pr_inf "Setting up root password to 'riscv'"
	chroot ${PREFIX} /bin/sh -c 'echo "riscv\nriscv" | passwd'

	echo "" > ${PREFIX}/etc/fstab

	# Things below may get stuck (but they can be fixed / done on reboot)

	pr_inf "Preparing/configuring package installer"
	# Mandb updates may get stuck during installs etc over NFS, so let's
	# leave it out. The index will get re-created through a systemd timer anyway
	# no need to do it on every package install (especialy not at this stage).
	rm ${PREFIX}/var/lib/man-db/auto-update
	# We don't need man pages / info / docs etc anyway, try to save space
	# and bandwidth, all this stuff is available online anyway, and more up-to date,
	# not to mention this runs under a host which probably has them already
	echo path-exclude /usr/share/doc/* > ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	# we need to keep copyright files for legal reasons
	echo path-include /usr/share/doc/*/copyright >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	echo path-exclude /usr/share/man/* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	echo path-exclude /usr/share/groff/* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	echo path-exclude /usr/share/info/* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	echo path-exclude /usr/share/lintian/* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	echo path-exclude /usr/share/linda/* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	# no need for localization, just keep en
	echo path-exclude /usr/share/locale/* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner
	echo path-include /usr/share/locale/en* >> ${PREFIX}/etc/dpkg/dpkg.cfg.d/01_cleaner

	pr_inf "Cleaning up the mess..."
	# Unfortunately dash doesn't support arrays, this is a mess to clean up more mess, mess all over the place...
	run_in_chroot apt-get purge -y apport apparmor appstream bcache-tools bolt cloud-guest-utils cloud-init cloud-initramfs-copymods cloud-initramfs-dyn-netconf eatmydata finalrd friendly-recovery fwupd modemmanager netplan-generator netplan.io open-iscsi snapd squashfs-tools tcl thin-provisioning-tools ubuntu-pro-client ufw unattended-upgrades mdadm udisks2 lxd-* multipath-tools plymouth* rsyslog pollinate lvm2
	run_in_chroot apt-get autoremove -y --purge
	run_in_chroot apt-get clean
	rm ${PREFIX}/etc/ssh/sshd_config.d/60-cloudimg-settings.conf
	# Cleanup any pre-installed man pages / docs, unused locales, translations etc
	pr_inf "Cleaning up disk space..."
	rm -rf ${PREFIX}/usr/share/man/*
	rm -rf ${PREFIX}/var/cache/man/*
	rm -rf ${PREFIX}/usr/share/info/*
	run_in_chroot locale-gen --purge en_US.UTF-8
	find ${PREFIX}/usr/share/doc -depth -type f ! -name copyright -print0 | xargs -0 rm &> /dev/null
	find ${PREFIX}/usr/share/doc -empty -print0 | xargs -0 rm -rf &> /dev/null
	find ${PREFIX}/usr/share/locale -mindepth 1 -maxdepth 1 ! -name en -print0 | xargs -0 rm -rf &> /dev/null

	pr_inf "Updating package list"
	run_in_chroot apt-get update

	# Networking is ours to manage only on a local-disk boot, where nothing set it
	# up for us: full DHCP on eth0 via networkd, DNS via resolved. Over NFS the
	# initramfs already brought eth0 up and the root rides on it, so keep
	# networkd/resolved disabled - they'd only fight what the initramfs did, and we
	# keep the static resolv.conf prepare_chroot left behind.
	if target_is_local; then
		pr_inf "Configuring systemd-networkd + systemd-resolved"
		echo -e "[Match]\nName=eth0\n\n[Network]\nDHCP=ipv4\n" > ${PREFIX}/etc/systemd/network/20-eth0.network
		# Mask the default .link so udev keeps the kernel's eth0 name (and MAC)
		# instead of renaming it - otherwise the Name=eth0 match above won't apply.
		ln -s /dev/null ${PREFIX}/etc/systemd/network/99-default.link
		run_in_chroot systemctl enable systemd-networkd
		run_in_chroot systemctl enable systemd-resolved
		# Hand resolv.conf back to resolved (prepare_chroot left a static copy).
		ln -sf ../run/systemd/resolve/stub-resolv.conf ${PREFIX}/etc/resolv.conf
	else
		pr_inf "Keeping systemd-networkd + systemd-resolved disabled (network from initramfs)"
		run_in_chroot systemctl disable systemd-networkd
		run_in_chroot systemctl disable systemd-resolved
	fi

	pr_inf "Disabling sysstat service"
	run_in_chroot systemctl disable sysstat

	pr_inf "Enabling ssh daemon and generating host keys"
	run_in_chroot dpkg-reconfigure openssh-server
	run_in_chroot systemctl enable ssh

	pr_inf "Installing dev environment packages"
	run_in_chroot apt-get install -y build-essential device-tree-compiler bison flex mpich autoconf automake gperf libtool net-tools

	# On a local-disk install, fstab is what actually mounts things on our current
	# -kernel/busybox-initramfs boot: systemd's DPS gpt-auto-generator runs before
	# any udev, so it can't enumerate the disk that early. We still lay down
	# everything DPS needs - type GUIDs, emptied mountpoints, and /var's
	# machine-id-keyed PARTUUID - so a future UEFI boot auto-mounts as-is. Over NFS
	# there are no local partitions, so the empty fstab above is all that's needed.
	if target_is_local; then
		write_fstab
		set_var_partuuid
	fi
}

########
# MAIN #
########

pr_ann "Installing Ubuntu Linux"
installer_common_main "$@"

pr_ann "Done"
halt
