#!/bin/bash
PREFIX=${1}
AUTO=0

##################
# CONSOLE OUTPUT #
##################

function pr_ann () {
	echo -e "\e[32m \n--=== ${1} ===--\e[0m"
}

function pr_inf () {
	echo -e "\e[36m${1}\e[0m"
}

function pr_wrn () {
	echo -e "\e[33m${1}\e[0m"
}

function pr_err () {
	>&2 echo -e "\e[31m${1}\e[0m"
}

###########
# HELPERS #
###########

function run_in_chroot() {
	chroot ${PREFIX} $@
}

###################
# INSTALLER STEPS #
###################

function timesync () {
	local HTTP_DATE_STRING=$(wget -qS www.google.com -O /dev/null 2>&1 | grep "Date:" | awk -F", " '{print $2}' | awk '{print $3"-"$2"-"$1" "$4}')
	local MONTH_STR=$(echo ${HTTP_DATE_STRING} | awk -F"-" '{print $2}')
	local MONTHS="JanFebMarAprMayJunJulAugSepOctNovDec"
	local MONTHS_TRIMMED=${MONTHS%%$MONTH_STR*}
	local MONTHS_TRIMMED_LEN=${#MONTHS_TRIMMED}
	local MONTH_NUM=$(printf "%02d" $((MONTHS_TRIMMED_LEN/3+1)))
	local DATE_STRING=$(echo ${HTTP_DATE_STRING} | sed -e "s/${MONTH_STR}/${MONTH_NUM}/g")
	pr_ann "Syncing time with google.com"
	pr_inf "Http date string: \"${HTTP_DATE_STRING}\""
	date -u "${DATE_STRING}"
}


function get_prefix_from_cmdline () {
	local CMDLINE_DEV=$(cat /proc/cmdline | awk -F "installer_dev=" '{print $2}' | awk '{print $1}')
	local CMDLINE_PREFIX=$(cat /proc/cmdline | awk -F "installer_prefix=" '{print $2}' | awk '{print $1}')

	# Bump up MTU and add default route via eth1 (DMA eth, user backend) for downloads
	ip link set eth1 down
	ip link set dev eth1 mtu 3626
	ip link set eth1 up
	ip route add default via 10.0.2.2

	if [[ "${CMDLINE_DEV}" != "" ]]; then
		pr_inf "Got installer device from kernel cmdline: ${CMDLINE_DEV}"
		PREFIX=/mnt/target
		mkdir -p ${PREFIX}

		pr_inf "Mounting ${CMDLINE_DEV} at ${PREFIX}"
		mount ${CMDLINE_DEV} ${PREFIX}
		if [[ $? != 0 ]]; then
			pr_err "Couldn't mount ${CMDLINE_DEV}"
			exit 1
		fi
		AUTO=1
	elif [[ "${CMDLINE_PREFIX}" != "" ]]; then
		pr_inf "Got installer prefix from kernel cmdline: ${CMDLINE_PREFIX}"
		pr_inf "Mounting NFS export to /mnt/target"
		PREFIX=/mnt/target
		mkdir -p ${PREFIX}
		mount -tnfs4 10.0.2.2:${CMDLINE_PREFIX} ${PREFIX}
		if [[ $? != 0 ]]; then
			pr_err "Couldn't mount NFS export"
			exit 1
		fi
		ls -lah ${PREFIX}/* &> /dev/null
		if [[ $? == 0 ]]; then
			pr_err "NFS Export not empty"
			exit 1
		fi
		AUTO=1
	else
		exit 1
	fi
}

function download_initrootfs () {
	local REL_URL="http://dl-cdn.alpinelinux.org/alpine/edge/releases/riscv64/"
	local FILE=$(wget -q -O- ${REL_URL}/latest-releases.yaml | grep "file:" | awk '{print $2}')
	local DOWNLOAD_URL=${REL_URL}/${FILE}
	local SAVED_PWD=${PWD}

	pr_ann "Downloading base rootfs..."

	mkdir -p ${PREFIX} &> /dev/null
	cd ${PREFIX}
	wget ${DOWNLOAD_URL}

	pr_ann "Unpacking base rootfs..."
#	tar xzpf ${FILE} --xattrs-include='*.*' --numeric-owner &> /dev/null
	tar xzf ${FILE} --numeric-owner &> /dev/null

	rm ${FILE}
	cd ${PWD}
}

function prepare_chroot () {
	pr_ann "Setting up chroot environment"

	pr_inf "Creating resolv.conf"
	echo "nameserver 10.0.2.3" > ${PREFIX}/etc/resolv.conf

	pr_inf "Mounting /proc"
	mount -t proc none ${PREFIX}/proc

	pr_inf "Mounting /dev"
	mount --rbind /dev ${PREFIX}/dev
	mount --make-rslave ${PREFIX}/dev

	pr_inf "Mounting /sys"
	mount --rbind /sys ${PREFIX}/sys
	mount --make-rslave ${PREFIX}/sys

	pr_inf "Mounting /run"
	if [[ -d /run ]]; then
		mount --rbind /run ${PREFIX}/run
		mount --make-rslave ${PREFIX}/run
	fi
}

function initialize_rootfs () {
	pr_ann "Initializing rootfs"

	pr_inf "Setting up apk repositories"
	echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > ${PREFIX}/etc/apk/repositories
	echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> ${PREFIX}/etc/apk/repositories

	pr_inf "Copying kernel modules"
	mkdir -p ${PREFIX}/lib/modules/
	cp -a /lib/modules/* ${PREFIX}/lib/modules/

	pr_inf "Installing alpine-base"
	run_in_chroot apk add --update alpine-base

	pr_inf "Configuring sysinit runlevel"
	run_in_chroot rc-update add devfs sysinit
	run_in_chroot rc-update add dmesg sysinit
	run_in_chroot rc-update add mdev sysinit
	run_in_chroot rc-update add hwdrivers sysinit

	pr_inf "Configuring boot runlelvel"
	run_in_chroot rc-update add modules boot
	run_in_chroot rc-update add sysctl boot
	run_in_chroot rc-update add hostname boot
	run_in_chroot rc-update add bootmisc boot
	run_in_chroot rc-update add syslog boot

	pr_inf "Configuring shutdown runlevel"
	run_in_chroot rc-update add mount-ro shutdown
	run_in_chroot rc-update add killprocs shutdown
	run_in_chroot rc-update add savecache shutdown

	run_in_chroot rc-update add firstboot default

	pr_inf "Adding some extra packages"
	run_in_chroot apk add xz ca-certificates

	pr_inf "Setting timezone to CET"
	run_in_chroot apk add tzdata
	run_in_chroot setup-timezone CET

	pr_inf "Setting keymap to us"
	run_in_chroot apk add kbd-bkeymaps
	run_in_chroot setup-keymap us us

	pr_inf "Configuring hostname/DNS"
	run_in_chroot setup-hostname riscv-alpine
	run_in_chroot setup-dns 10.0.2.3

        pr_inf "Configuring networking (loopback only)"
        echo "auto lo" > ${PREFIX}/etc/network/interfaces
        echo "iface lo inet loopback" >> ${PREFIX}/etc/network/interfaces

	pr_inf "Setting up SSH"
	run_in_chroot setup-sshd openssh

	pr_inf "Setting up NTP"
	run_in_chroot setup-ntp chrony

	pr_inf "Setting up root password to 'riscv'"
	chroot ${PREFIX} /bin/sh -c 'echo -e "riscv\nriscv" | passwd'

	pr_inf "Configuring console"
	sed -i '/ttyS0/s/^#//g' ${PREFIX}/etc/inittab
}

function cleanup () {
	sync;sync

	pr_inf "Unmounting /proc"
	for i in $(mount | grep ${PREFIX}/proc | awk '{print $3}'); do
		umount ${i} &> /dev/null
	done
	umount ${PREFIX}/proc &> /dev/null

	pr_inf "Unmounting /dev"
	for i in $(mount | grep ${PREFIX}/dev | awk '{print $3}'); do
                umount ${i} &> /dev/null
        done
	umount -l ${PREFIX}/dev &> /dev/null

	pr_inf "Unmounting /sys"
	for i in $(mount | grep ${PREFIX}/sys | awk '{print $3}'); do
		umount ${i} &> /dev/null
	done
	umount ${PREFIX}/sys &> /dev/null

	if [[ -d /run ]]; then
		pr_inf "Unmounting /run"
		for i in $(mount | grep ${PREFIX}/run | awk '{print $3}'); do
			umount ${i} &> /dev/null
		done
		umount ${PREFIX}/run
	fi

	sync
	pr_inf "Unmounting target"
	umount ${PREFIX} &> /dev/null
}

if [[ $# != 1 ]]; then
	pr_wrn "Installation prefix not provided"
	get_prefix_from_cmdline
fi

timesync
download_initrootfs
prepare_chroot
initialize_rootfs
cleanup

pr_ann "Done"
if [[ ${AUTO} == 1 ]]; then
	halt
fi
